#ifndef tadpole1L_pysecdec_integral_codegen_optimize_deformation_parameters_sector_1_order_1_hpp_included
#define tadpole1L_pysecdec_integral_codegen_optimize_deformation_parameters_sector_1_order_1_hpp_included
#include "tadpole1L_pysecdec_integral.hpp"
#include "functions.hpp"
#include <cmath>
#include <limits>
#include <vector>
namespace tadpole1L_pysecdec_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::MaximalDeformationFunction sector_1_order_1_maximal_allowed_deformation_parameters;
};
#endif
