#ifndef triangle1L_massive_pysecdec_integral_codegen_optimize_deformation_parameters_sector_1_order_0_hpp_included
#define triangle1L_massive_pysecdec_integral_codegen_optimize_deformation_parameters_sector_1_order_0_hpp_included
#include "triangle1L_massive_pysecdec_integral.hpp"
#include "functions.hpp"
#include <cmath>
#include <limits>
#include <vector>
namespace triangle1L_massive_pysecdec_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::MaximalDeformationFunction sector_1_order_0_maximal_allowed_deformation_parameters;
};
#endif
