#ifndef B0_standard_pysecdec_integral_codegen_contour_deformation_sector_2_order_0_hpp_included
#define B0_standard_pysecdec_integral_codegen_contour_deformation_sector_2_order_0_hpp_included
#include "B0_standard_pysecdec_integral.hpp"
#include "functions.hpp"
namespace B0_standard_pysecdec_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::DeformedIntegrandFunction sector_2_order_0_contour_deformation_polynomial;
};
#endif
