#ifndef B0_standard_pysecdec_integral_codegen_optimize_deformation_parameters_sector_2_order_0_hpp_included
#define B0_standard_pysecdec_integral_codegen_optimize_deformation_parameters_sector_2_order_0_hpp_included
#include "B0_standard_pysecdec_integral.hpp"
#include "functions.hpp"
#include <cmath>
#include <limits>
#include <vector>
namespace B0_standard_pysecdec_integral
{
secdecutil::SectorContainerWithDeformation<real_t, complex_t>::MaximalDeformationFunction sector_2_order_0_maximal_allowed_deformation_parameters;
};
#endif
